Repository mainmatter/ember-intl-analyzer, pull requests merged in 2019-08, with the labels that each got.

#51 Use non-zero exit code when problems are found
  bin/cli.js
  index.js
  test.js
Labels: breaking, enhancement

#58 Adds YAML support
  __snapshots__/test.js.snap
  fixtures/yaml-translations/app/controllers/application.js
  fixtures/yaml-translations/app/templates/application.hbs
  fixtures/yaml-translations/translations/de.yaml
  fixtures/yaml-translations/translations/en.yaml
  index.js
  package.json
Labels: enhancement

#59 Fix process exit code assignment
  bin/cli.js
Labels: bug
